---

- name: Upgrade system
  apt: upgrade=dist update_cache=yes

- name: Install curl
  apt: name=curl state=latest

- name: Install openssh-server
  apt: name=openssh-server state=latest

- name: Install ca-certificates
  apt: name=ca-certificates state=latest

- name: Install postfix
  apt: name=postfix state=latest

- name: Install python-boto
  apt: name=python-boto state=latest

- name: Add the GitLab package repository and install the package
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash

- name: Install gitlab
  apt: name=gitlab-ee state=latest

- name: Remove default gitlab config
  file: name=/etc/gitlab/gitlab.rb state=absent

- name: Install gitlab config
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb

- name: Reconfigure and restart GitLab
  shell: gitlab-ctl reconfigure && gitlab-ctl restart

- name: Download bucket content
  gc_storage:
    bucket: '{{ gcloud_storage_name }}'
    object: '{{ gcloud_tar_name }}'
    dest: /home/{{ ansible_user }}/{{ gcloud_tar_name }}
    gs_access_key: '{{ gcloud_storage_key }}'
    gs_secret_key: '{{ gcloud_storage_secret_key }}'
    mode: get

- name: Move repository backup file
  shell: mv {{ gcloud_tar_name }} /var/opt/gitlab/backups/{{ gcloud_tar_name }}

- name: Give file permissions to the necessary user
  shell: chown git.git /var/opt/gitlab/backups/{{ gcloud_tar_name }}

- name: Stop unicorn
  shell: gitlab-ctl stop unicorn

- name: Stop puma
  shell: gitlab-ctl stop puma

- name: Stop sidekiq
  shell: gitlab-ctl stop sidekiq

- name: Make backup restore
  shell: gitlab-backup restore BACKUP='{{ gcloud_bucket_name }}' force=yes

- name: Reconfigure and restart GitLab
  shell: gitlab-ctl reconfigure && gitlab-ctl restart
...
